import type { FilterOperator } from "../types";
import type { Stock } from "../types";

export type FilterKind = "range" | "multi" | "single" | "boolean";

export interface FilterDefinition {
  id: string;
  label: string;
  field: keyof Stock;
  operator: FilterOperator;
  kind: FilterKind;
  min?: number;
  max?: number;
  options?: string[];
  category:
    | "Fundamentals"
    | "Market Data"
    | "Classification"
    | "Technical"
    | "Custom";
}

export const FILTER_DEFINITIONS: FilterDefinition[] = [
  {
    id: "marketCap",
    label: "Market Capitalisation (Cr)",
    field: "marketCap",
    operator: "between",
    kind: "range",
    min: 0,
    max: 5000000,
    category: "Fundamentals",
  },
  {
    id: "pe",
    label: "P/E Ratio",
    field: "pe",
    operator: "between",
    kind: "range",
    min: -100,
    max: 500,
    category: "Fundamentals",
  },
  {
    id: "pb",
    label: "P/B Ratio",
    field: "pb",
    operator: "between",
    kind: "range",
    min: 0,
    max: 100,
    category: "Fundamentals",
  },
  {
    id: "dividendYield",
    label: "Dividend Yield (%)",
    field: "dividendYield",
    operator: "between",
    kind: "range",
    min: 0,
    max: 25,
    category: "Fundamentals",
  },
  {
    id: "eps",
    label: "EPS",
    field: "eps",
    operator: "between",
    kind: "range",
    min: -500,
    max: 5000,
    category: "Fundamentals",
  },
  {
    id: "roe",
    label: "ROE (%)",
    field: "roe",
    operator: "between",
    kind: "range",
    min: -100,
    max: 200,
    category: "Fundamentals",
  },
  {
    id: "roce",
    label: "ROCE (%)",
    field: "roce",
    operator: "between",
    kind: "range",
    min: -100,
    max: 200,
    category: "Fundamentals",
  },
  {
    id: "debtToEquity",
    label: "Debt/Equity",
    field: "debtToEquity",
    operator: "between",
    kind: "range",
    min: 0,
    max: 15,
    category: "Fundamentals",
  },
  {
    id: "currentRatio",
    label: "Current Ratio",
    field: "currentRatio",
    operator: "between",
    kind: "range",
    min: 0,
    max: 20,
    category: "Fundamentals",
  },
  {
    id: "promoterHolding",
    label: "Promoter Holding (%)",
    field: "promoterHolding",
    operator: "between",
    kind: "range",
    min: 0,
    max: 100,
    category: "Fundamentals",
  },
  {
    id: "revenueGrowthYoY",
    label: "Revenue Growth YoY (%)",
    field: "revenueGrowthYoY",
    operator: "between",
    kind: "range",
    min: -100,
    max: 500,
    category: "Fundamentals",
  },
  {
    id: "profitGrowthYoY",
    label: "Profit Growth YoY (%)",
    field: "profitGrowthYoY",
    operator: "between",
    kind: "range",
    min: -100,
    max: 1000,
    category: "Fundamentals",
  },
  {
    id: "lastPrice",
    label: "Last Traded Price",
    field: "lastPrice",
    operator: "between",
    kind: "range",
    min: 0,
    max: 500000,
    category: "Market Data",
  },
  {
    id: "week52HighProximity",
    label: "52W High Proximity (%)",
    field: "week52HighProximity",
    operator: "between",
    kind: "range",
    min: 0,
    max: 100,
    category: "Market Data",
  },
  {
    id: "week52LowProximity",
    label: "52W Low Proximity (%)",
    field: "week52LowProximity",
    operator: "between",
    kind: "range",
    min: 0,
    max: 100,
    category: "Market Data",
  },
  {
    id: "avgVolume20D",
    label: "Average Volume (20D)",
    field: "avgVolume20D",
    operator: "between",
    kind: "range",
    min: 0,
    max: 100000000,
    category: "Market Data",
  },
  {
    id: "beta",
    label: "Beta",
    field: "beta",
    operator: "between",
    kind: "range",
    min: -2,
    max: 5,
    category: "Market Data",
  },
  {
    id: "changePercent",
    label: "Day Change (%)",
    field: "changePercent",
    operator: "between",
    kind: "range",
    min: -20,
    max: 20,
    category: "Market Data",
  },
  {
    id: "sector",
    label: "Sector",
    field: "sector",
    operator: "in",
    kind: "multi",
    options: [
      "IT",
      "Banking",
      "Pharma",
      "Auto",
      "FMCG",
      "Metal",
      "Energy",
      "Realty",
      "Telecom",
      "Infrastructure",
      "Media",
      "Others",
    ],
    category: "Classification",
  },
  {
    id: "industry",
    label: "Industry",
    field: "industry",
    operator: "in",
    kind: "multi",
    options: [
      "IT Core",
      "Banking Core",
      "Pharma Core",
      "Auto Core",
      "FMCG Core",
      "Metal Core",
      "Energy Core",
      "Realty Core",
      "Telecom Core",
      "Infrastructure Core",
      "Media Core",
      "Others Core",
    ],
    category: "Classification",
  },
  {
    id: "marketCapCategory",
    label: "Market Cap Category",
    field: "marketCapCategory",
    operator: "in",
    kind: "multi",
    options: ["Large Cap", "Mid Cap", "Small Cap", "Micro Cap"],
    category: "Classification",
  },
  {
    id: "indexMembership",
    label: "Index Membership",
    field: "indexMembership",
    operator: "contains",
    kind: "multi",
    options: [
      "NIFTY 50",
      "NIFTY Next 50",
      "NIFTY Midcap 100",
      "NIFTY Smallcap 250",
      "BSE Sensex",
    ],
    category: "Classification",
  },
  {
    id: "rsi14",
    label: "RSI (14)",
    field: "rsi14",
    operator: "between",
    kind: "range",
    min: 0,
    max: 100,
    category: "Technical",
  },
  {
    id: "macdSignal",
    label: "MACD Signal",
    field: "macdSignal",
    operator: "eq",
    kind: "single",
    options: ["Bullish", "Bearish", "Neutral"],
    category: "Technical",
  },
  {
    id: "priceVsSma50",
    label: "Price vs SMA 50",
    field: "sma50",
    operator: "gt",
    kind: "single",
    options: ["Above", "Below"],
    category: "Technical",
  },
  {
    id: "priceVsSma200",
    label: "Price vs SMA 200",
    field: "sma200",
    operator: "gt",
    kind: "single",
    options: ["Above", "Below"],
    category: "Technical",
  },
  {
    id: "bollingerPosition",
    label: "Bollinger Position",
    field: "bollingerPosition",
    operator: "eq",
    kind: "single",
    options: ["Above", "Within", "Below"],
    category: "Technical",
  },
  {
    id: "atr",
    label: "ATR",
    field: "atr",
    operator: "between",
    kind: "range",
    min: 0,
    max: 500,
    category: "Technical",
  },
  {
    id: "volumeVsAvg",
    label: "Volume vs 20D Avg",
    field: "volumeVsAvg",
    operator: "eq",
    kind: "single",
    options: ["Below", "Above", "2x", "3x"],
    category: "Technical",
  },
  {
    id: "watchlist",
    label: "Watchlist Only",
    field: "watchlist",
    operator: "eq",
    kind: "boolean",
    category: "Custom",
  },
  {
    id: "recentlyUpdated",
    label: "Recently Updated",
    field: "recentlyUpdated",
    operator: "eq",
    kind: "boolean",
    category: "Custom",
  },
];
